default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary: &primary_production
    adapter: sqlite3
    database: storage/production.sqlite3
    migrations_paths: db/migrate
  cable:
    <<: *primary_production
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *primary_production
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate